apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker
  labels:
    app: spark
    role: worker
spec:
  replicas: 3  # Number of worker nodes
  selector:
    matchLabels:
      app: spark
      role: worker
  template:
    metadata:
      labels:
        app: spark
        role: worker
    spec:
      containers:
        - name: spark-worker
          image: bitnami/spark:latest
          ports:
            - containerPort: 8081  # Spark worker web UI port
          env:
            - name: SPARK_MODE
              value: "worker"
            - name: SPARK_MASTER_URL
              value: "spark://spark-master:7077"
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "1"
          volumeMounts:
            - name: spark-data
              mountPath: /opt/spark/data
      volumes:
        - name: spark-data
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: spark-worker
  labels:
    app: spark
    role: worker
spec:
  ports:
    - port: 8081
      name: webui
  selector:
    app: spark
    role: worker
